site_name: Hishel
repo_url: https://github.com/karosis88/hishel

theme:
  name: material
  features:
    - content.code.copy
  palette:
    - scheme: default
      primary: "amber"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: "amber"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: sphinx
          docstring_section_style: table
nav:
  - Introduction: index.md
  - User Guide: userguide.md
  - API Reference: api.md